### ISSUE TITLE
commands to manage wallet accounts

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-cli#8]
Reference https://github.com/ethereum/go-ethereum/blob/master/cmd/geth/accountcmd.go

We currently use
- ecdsa

1. get accounts
```shell
bc-cli get accounts --wallet ~/.bestchains/wallet
```
2. create account
```
bc-cli create account  --wallet ~/.bestchains/wallet
```
4. delete account
```
bc-cli delete account --wallet ~/.bestchains/wallet  {account_address}
```

**Comment by 0xff-dev** [comment]
```json
{"address":"b7f5a632ae0d561c6609be8507b1bdde0d669a59","crypto":{"cipher":"aes-128-ctr","ciphertext":"6670befcd092d4e57b0d19560c802660b83483d308abe12a749da1d72d98bc84","cipherparams":{"iv":"9a52fa38e51deabb43d0df9f1bb502f9"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"51364fc5fdae858cef2d70e4c0072b3704581bb39c199dd5c08108b323a8687d"},"mac":"e9e7c7cd37d47bd4557f9726ce380513cfc8d8c6ba283a21e518ee532889102c"},"id":"0c4cab9a-1b00-40d9-a8d0-cb50b6e0e11b","version":3}
```

**Comment by bjwswang** [comment]
> ```json
> {"address":"b7f5a632ae0d561c6609be8507b1bdde0d669a59","crypto":{"cipher":"aes-128-ctr","ciphertext":"6670befcd092d4e57b0d19560c802660b83483d308abe12a749da1d72d98bc84","cipherparams":{"iv":"9a52fa38e51deabb43d0df9f1bb502f9"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"51364fc5fdae858cef2d70e4c0072b3704581bb39c199dd5c08108b323a8687d"},"mac":"e9e7c7cd37d47bd4557f9726ce380513cfc8d8c6ba283a21e518ee532889102c"},"id":"0c4cab9a-1b00-40d9-a8d0-cb50b6e0e11b","version":3}
> ```


etherem use a password to encrypt priv key before store it into local file which is not must required for us. we only need to keep 
```
{
  "address": "",
   "privKey": ""
}
```
1. address computation in https://github.com/bestchains/bestchains-contracts/blob/main/library/address.go#L58
2. For privKey, we can save it as base64 encoded string
